Repository qxb3/fum, pull requests merged in 2025-01, with the labels that each got.

#9 chore: Add keystrokes to README.md
  README.md
Labels: documentation

#15 full rewrite of the ui
  Cargo.lock
  Cargo.toml
  src/cli.rs
  src/config.rs
  src/config/config.rs
  src/config/defaults.rs
  src/config/mod.rs
  src/fum.rs
  src/main.rs
  src/meta.rs
  src/term_config.rs
  src/ui.rs
  src/utils.rs
  src/utils/align.rs
  src/utils/etc.rs
  src/utils/mod.rs
  src/utils/player.rs
  src/utils/terminal.rs
  src/widget.rs
Labels: enhancement

#18 more metadata
  Cargo.lock
  Cargo.toml
  src/meta.rs
  src/ui.rs
  src/utils/player.rs
Labels: enhancement

#24 fix: truncate function
  src/utils/etc.rs
Labels: bug

#25 fix resize update
  src/fum.rs
Labels: bug

#29 Keybinds
  src/action.rs
  src/config/config.rs
  src/config/defaults.rs
  src/config/keybind.rs
  src/config/mod.rs
  src/fum.rs
  src/ui.rs
Labels: enhancement

#33 forward() & backward() actions
  src/action.rs
Labels: enhancement

#34 added bg and bg on widgets
  Cargo.lock
  Cargo.toml
  src/config/config.rs
  src/config/defaults.rs
  src/ui.rs
  src/utils/etc.rs
  src/widget.rs
Labels: enhancement

#36 forward(), backward() action improvements
  src/action.rs
  src/meta.rs
Labels: enhancement

#37 seperate color for progress and empty
  src/config/defaults.rs
  src/ui.rs
  src/widget.rs
Labels: enhancement

#39 Ratatui widget
  README.md
  nix/hm-module.nix
  src/action.rs
  src/config/config.rs
  src/config/defaults.rs
  src/fum.rs
  src/main.rs
  src/meta.rs
  src/text.rs
  src/ui.rs
  src/utils/terminal.rs
  src/widget/button.rs
  src/widget/container.rs
  src/widget/cover_art.rs
  src/widget/empty.rs
  src/widget/label.rs
  src/widget/mod.rs
  src/widget/progress.rs
  src/widget/widget.rs
Labels: enhancement

#41 introducing variable
  Cargo.lock
  Cargo.toml
  src/action.rs
  src/fum.rs
  src/main.rs
  src/regexes.rs
  src/state.rs
  src/text.rs
  src/ui.rs
  src/utils/etc.rs
  src/widget/button.rs
  src/widget/container.rs
  src/widget/cover_art.rs
  src/widget/empty.rs
  src/widget/label.rs
  src/widget/progress.rs
  src/widget/widget.rs
Labels: enhancement

#45 Cover art ascii
  src/config/config.rs
  src/config/defaults.rs
  src/state.rs
  src/ui.rs
  src/widget/cover_art.rs
Labels: enhancement

#47 Handle unicode width
  Cargo.lock
  Cargo.toml
  src/widget/widget.rs
Labels: bug

#48 default config update
  src/config/defaults.rs
Labels: enhancement
